FROM python:3.11-slim-buster

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./src /app/src
COPY ./model /app/model
COPY ./data/text_bot.txt /app/data/text_bot.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ENV PYTHONUNBUFFERED 1

EXPOSE 84

CMD ["python", "src/ruDialoGPT-bot.py"]